//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMXBasicCRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartNumber
    {
        public int PartNumberId { get; set; }
        public string Name { get; set; }
        public string InvoiceDescription { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string InventoryPartNumber { get; set; }
        public string ManufacturerPartNumber { get; set; }
        public string CategoryCustomData { get; set; }
        public string ManufacturerCustomData { get; set; }
        public Nullable<decimal> ListPrice { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string UPC { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual Model Model { get; set; }
        public virtual Status Status { get; set; }
    }
}
